name: Publish docs to Wiki

on:
  push:
    paths:
      - .github/wiki/**
    branches:
      - main

jobs:
  publish_docs_to_wiki:
    name: Publish docs to Wiki
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Publish Github Wiki
        uses: nimblehq/publish-github-wiki-action@v1.0
        with:
          user_name: team-nimblehq
          user_email: dev@nimblehq.co
          user_access_token: ${{ secrets.WIKI_ACTION_TOKEN }}
